#!/usr/bin/env php
<?php
    // Make sure we have a param
    if (empty($argv[1])) {
        throw new \Exception("Needs a param");
    }

    // Underp the base64 that the param is using.
    $b = str_replace('_', '/', $argv[1]);
    $settings = @json_decode(gzuncompress(@base64_decode($b)), true);

    if (!is_array($settings)) {
        throw new \Exception("Invalid param");
    }
    
    $action = empty($settings["action"]) ? ""   : $settings["action"] ;
    $ip     = empty($settings["ip"])     ? ""   : $settings["ip"];
    if (!filter_var($ip, \FILTER_VALIDATE_IP)) {
	    throw new \Exception("Not an IP address");
    }

    $FC     = "/usr/bin/fail2ban-client";
    $cmd    = "$FC status | grep 'Jail list' | sed -r 's/.+Jail list:\t+//g' | sed -e 's/ *//g' -e 's/\,/\\n/g'";
    exec($cmd, $out, $ret);
    if($ret === 0 && is_array($out)){
        foreach($out as $jail){
            $d = @date("Y-m-d H:i:s");
            switch($action){
                case "addignoreip" :
                    exec("$FC get $jail ignoreip | grep - | cut -d' ' -f2 | uniq", $out2);
                    if(array_search($ip, $out2) === false){
                        exec("$FC set $jail $action $ip");                       
                    }
                    break;
                case "delignoreip" :
                    exec("$FC get $jail ignoreip | grep - | cut -d' ' -f2 | uniq", $out2);
                    if(array_search($ip, $out2) !== false){
                        exec("$FC set $jail $action $ip");
                    }
                    break;
                case "banip" :
                    exec("$FC status $jail | grep 'IP list:' | cut -f2", $out2);
                    if(strpos($out2[0], $ip) !== true){
                        exec("$FC set $jail $action $ip");                       
                    }
                    break;
                case "unbanip" :
                    exec("$FC status $jail | grep 'IP list:' | cut -f2", $out2);                    
                    if(strpos($out2[0], $ip) !== false){
                        exec("$FC set $jail $action $ip");
                    }
                    break;
                default:
                    $log = strintf(_("No action defined such as %s."), $action);
                    exec("echo $log >> /var/log/fail2ban.log");
            }
            unset($out2);
        }
    }
    
?>
