#!/usr/bin/env php
<?php
// vim: :set filetype=php tabstop=4 shiftwidth=4 autoindent smartindent:

// TEMPORARY: Kill old firewalld if it's running
exec("pgrep -f hooks/firewall", $out, $ret);
if ($ret === 0) {
	$pid = (int) $out[0];
	if ($pid > 10) {
		posix_kill($pid, -9);
	}
}

require '/usr/lib/sysadmin/includes.php';
$g = new \Sysadmin\GPG();
$sigfile = __DIR__."/../module.sig";
$sig = $g->checkSig($sigfile);
if (!isset($sig['config']['hash']) || $sig['config']['hash'] !== "sha256") {
	throw new \Exception("Invalid sig file.. Hash is not sha256 - check $sigfile");
}

// Check the hash of the validator, before we include it
if (empty($sig['hashes']['hooks/voipfirewalld'])) {
	throw new \Exception("Firewalld not part of module.sig");
}

$fd = __DIR__."/voipfirewalld";

$fhash = hash_file('sha256', $fd);
if ($fhash !== $sig['hashes']['hooks/voipfirewalld']) {
	throw new \Exception("Firewalld tampered");
}

// Move the previous logfile out of the way.
@unlink("/tmp/firewall.log.previous");
rename ("/tmp/firewall.log", "/tmp/firewall.log.previous");
// Start the daemon
exec("nohup $fd &>> /tmp/firewall.log &");
