#!/usr/bin/env php
<?php

require '/usr/lib/sysadmin/includes.php';

$iptables 		= json_encode(getNativeFirewallState());
$astspooldir	= \Sysadmin\FreePBX::Config()->get('ASTSPOOLDIR');

if (is_dir("/run")) {
	$out = "/run/iptables.out";
} else {
	$out = $astspooldir."/tmp/iptables.out";
}

if (file_exists($out)) {
	unlink($out);
}

file_put_contents($out, $iptables);
chmod($out, 0777);

function getNativeFirewallState() {
	$nft = is_executable('/usr/sbin/nft') ? '/usr/sbin/nft' : '/sbin/nft';
	if (!is_executable($nft)) {
		throw new \RuntimeException('nftables is required');
	}
	exec(escapeshellcmd($nft).' -j list table inet fpbx 2>/dev/null', $output, $ret);
	$interfaces = array();
	if ($ret === 0) {
		$json = json_decode(implode("\n", $output), true);
		foreach ($json['nftables'] ?? array() as $item) {
			if (($item['rule']['chain'] ?? '') !== 'fpbxinterfaces') {
				continue;
			}
			$iface = null;
			$zone = null;
			foreach ($item['rule']['expr'] ?? array() as $expr) {
				if (($expr['match']['left']['meta']['key'] ?? '') === 'iifname') {
					$iface = $expr['match']['right'] ?? null;
				}
				if (strpos($expr['jump']['target'] ?? '', 'zone-') === 0) {
					$zone = substr($expr['jump']['target'], 5);
				}
			}
			if ($iface && $zone) {
				$interfaces[] = '-i '.$iface.' -j zone-'.$zone;
			}
		}
	}
	$conf = array(
		"ipv4" => array("filter" => array("fpbxinterfaces" => $interfaces), "nat" => array()),
		"ipv6" => array("filter" => array("fpbxinterfaces" => $interfaces)),
		"timestamp" => time(),
	);
	return $conf;
}

