#!/usr/bin/env php
<?php
// vim: :set filetype=php tabstop=4 shiftwidth=4 autoindent smartindent:

// Make sure we have a param
if (empty($argv[1])) {
	throw new \Exception("Needs a param");
}

// Underp the base64 that the param is using.
$b = str_replace('_', '/', $argv[1]);
$settings = @json_decode(gzuncompress(@base64_decode($b)), true);

if (!is_array($settings)) {
	throw new \Exception("Invalid param");
}

// Make sure our host is an IP address
if (!filter_var($settings['unblock'], \FILTER_VALIDATE_IP)) {
	throw new \Exception("Not an IP address");
}

$ip = $settings['unblock'];
$nft = is_executable('/usr/sbin/nft') ? '/usr/sbin/nft' : '/sbin/nft';
if (!is_executable($nft)) {
	throw new \Exception("nftables is required");
}
$suffix = filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? '6' : '';
$sets = array('rfw_attacker', 'rfw_clamped', 'rfw_tempwhitelist', 'rfw_whitelist', 'rfw_discovered');
foreach ($sets as $set) {
	$cmd = escapeshellcmd($nft).' delete element inet fpbx '.$set.$suffix.' { '.$ip.' } 2>/dev/null';
	exec($cmd);
}

if (!empty($settings['login'])) {
	$set = 'registrations'.$suffix;
	$cmd = escapeshellcmd($nft).' add element inet fpbx '.$set.' { '.$ip.' } 2>/dev/null';
	exec($cmd);
}


