#!/bin/bash

# Find the voipfirewalld process
PID=`pgrep -f voipfirewalld`

# Kill it dead.

if [ "$PID" ]; then
	kill -9 $PID
fi

# Clean up any iptables rules
service iptables stop
service ip6tables stop




