#!/bin/bash

# Find the voipfirewalld process
PID=`pgrep -f voipfirewalld`

# Kill it dead.

if [ "$PID" ]; then
	kill -9 $PID
fi

# Clean up any iptables rules
service iptables stop
service ip6tables stop
grep xt_recent /proc/modules && rmmod xt_recent
grep ipt_recent /proc/modules && rmmod ipt_recent

